export enum ClassName {
  EMPTY = '',
  GRASS = 'grass',
  SIDEWALK = 'sidewalk',
  ROAD = 'road',
  CROSSROAD = 'crossroad',
  CROSSWALK = 'crosswalk',
  RED_CROSSWALK = 'red-crosswalk',
  GREEN_CROSSWALK = 'green-crosswalk',
  CAR = 'car',
  MAN = 'man',
  UP = 'up',
  DOWN = 'down',
  LEFT = 'left',
  RIGHT = 'right',
}
